### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by Pytal**
Addendum to #24

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by skjnldsv** [comment]
Removing `@babel/plugin-proposal-class-properties` broke custom classes like https://github.com/nextcloud/viewer/blob/dbfa6bc8ead717530001a981b7d442510bf8d897/src/services/Viewer.js#L29-L30

**Comment by skjnldsv** [comment]
image

**Comment by Pytal** [comment]
> @Pytal removing `@babel/plugin-proposal-class-properties` broke custom classes like https://github.com/nextcloud/viewer/blob/dbfa6bc8ead717530001a981b7d442510bf8d897/src/services/Viewer.js#L29-L30

Fixed in https://github.com/nextcloud/babel-config/pull/30

**Comment by Pytal** [comment]
> @Pytal removing `@babel/plugin-proposal-class-properties` broke custom classes like https://github.com/nextcloud/viewer/blob/dbfa6bc8ead717530001a981b7d442510bf8d897/src/services/Viewer.js#L29-L30

Fixed in https://github.com/nextcloud/babel-config/pull/30 :)

**Pull request merged**
